### ISSUE TITLE
Attribution for Giphy is missing

### ISSUE THREAD

**Issue by xinyi-joffre** [alancast/RandomGifBot#15]
Before we apply for production key, the following requirement has to be met: 

> As per our section 5 A of our terms of service, we require all apps that use the GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized. You can find approved official logo marks [here](https://www.google.com/url?q=http%3A%2F%2Fgiphymedia.s3.amazonaws.com%2Fgiphy-attribution-marks.zip&sa=D&sntz=1&usg=AFQjCNH2vioX4nvSrL6iR2kuB_WG-85VLA). Please provide screenshots of your attribution placement.

Maybe we can add the attribution as a caption to the hero card?

**Comment by alancast** [comment]
Closed by PR #20
